//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAPService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.webserviceX.NET", ConfigurationName="SOAPService.BibleWebserviceSoap")]
    public interface BibleWebserviceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetBibleWordsByChapterAndVerse", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPService.GetBibleWordsByChapterAndVerseResponse> GetBibleWordsByChapterAndVerseAsync(SOAPService.GetBibleWordsByChapterAndVerseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetBibleWordsbyKeyWord", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPService.GetBibleWordsbyKeyWordResponse> GetBibleWordsbyKeyWordAsync(SOAPService.GetBibleWordsbyKeyWordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetBookTitles", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPService.GetBookTitlesResponse> GetBookTitlesAsync(SOAPService.GetBookTitlesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetBibleWordsByBookTitleAndChapter", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPService.GetBibleWordsByBookTitleAndChapterResponse> GetBibleWordsByBookTitleAndChapterAsync(SOAPService.GetBibleWordsByBookTitleAndChapterRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBibleWordsByChapterAndVerseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBibleWordsByChapterAndVerse", Namespace="http://www.webserviceX.NET", Order=0)]
        public SOAPService.GetBibleWordsByChapterAndVerseRequestBody Body;
        
        public GetBibleWordsByChapterAndVerseRequest()
        {
        }
        
        public GetBibleWordsByChapterAndVerseRequest(SOAPService.GetBibleWordsByChapterAndVerseRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
    public partial class GetBibleWordsByChapterAndVerseRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BookTitle;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int chapter;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Verse;
        
        public GetBibleWordsByChapterAndVerseRequestBody()
        {
        }
        
        public GetBibleWordsByChapterAndVerseRequestBody(string BookTitle, int chapter, int Verse)
        {
            this.BookTitle = BookTitle;
            this.chapter = chapter;
            this.Verse = Verse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBibleWordsByChapterAndVerseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBibleWordsByChapterAndVerseResponse", Namespace="http://www.webserviceX.NET", Order=0)]
        public SOAPService.GetBibleWordsByChapterAndVerseResponseBody Body;
        
        public GetBibleWordsByChapterAndVerseResponse()
        {
        }
        
        public GetBibleWordsByChapterAndVerseResponse(SOAPService.GetBibleWordsByChapterAndVerseResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
    public partial class GetBibleWordsByChapterAndVerseResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBibleWordsByChapterAndVerseResult;
        
        public GetBibleWordsByChapterAndVerseResponseBody()
        {
        }
        
        public GetBibleWordsByChapterAndVerseResponseBody(string GetBibleWordsByChapterAndVerseResult)
        {
            this.GetBibleWordsByChapterAndVerseResult = GetBibleWordsByChapterAndVerseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBibleWordsbyKeyWordRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBibleWordsbyKeyWord", Namespace="http://www.webserviceX.NET", Order=0)]
        public SOAPService.GetBibleWordsbyKeyWordRequestBody Body;
        
        public GetBibleWordsbyKeyWordRequest()
        {
        }
        
        public GetBibleWordsbyKeyWordRequest(SOAPService.GetBibleWordsbyKeyWordRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
    public partial class GetBibleWordsbyKeyWordRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BibleWords;
        
        public GetBibleWordsbyKeyWordRequestBody()
        {
        }
        
        public GetBibleWordsbyKeyWordRequestBody(string BibleWords)
        {
            this.BibleWords = BibleWords;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBibleWordsbyKeyWordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBibleWordsbyKeyWordResponse", Namespace="http://www.webserviceX.NET", Order=0)]
        public SOAPService.GetBibleWordsbyKeyWordResponseBody Body;
        
        public GetBibleWordsbyKeyWordResponse()
        {
        }
        
        public GetBibleWordsbyKeyWordResponse(SOAPService.GetBibleWordsbyKeyWordResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
    public partial class GetBibleWordsbyKeyWordResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBibleWordsbyKeyWordResult;
        
        public GetBibleWordsbyKeyWordResponseBody()
        {
        }
        
        public GetBibleWordsbyKeyWordResponseBody(string GetBibleWordsbyKeyWordResult)
        {
            this.GetBibleWordsbyKeyWordResult = GetBibleWordsbyKeyWordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookTitlesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookTitles", Namespace="http://www.webserviceX.NET", Order=0)]
        public SOAPService.GetBookTitlesRequestBody Body;
        
        public GetBookTitlesRequest()
        {
        }
        
        public GetBookTitlesRequest(SOAPService.GetBookTitlesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetBookTitlesRequestBody
    {
        
        public GetBookTitlesRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookTitlesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookTitlesResponse", Namespace="http://www.webserviceX.NET", Order=0)]
        public SOAPService.GetBookTitlesResponseBody Body;
        
        public GetBookTitlesResponse()
        {
        }
        
        public GetBookTitlesResponse(SOAPService.GetBookTitlesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
    public partial class GetBookTitlesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBookTitlesResult;
        
        public GetBookTitlesResponseBody()
        {
        }
        
        public GetBookTitlesResponseBody(string GetBookTitlesResult)
        {
            this.GetBookTitlesResult = GetBookTitlesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBibleWordsByBookTitleAndChapterRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBibleWordsByBookTitleAndChapter", Namespace="http://www.webserviceX.NET", Order=0)]
        public SOAPService.GetBibleWordsByBookTitleAndChapterRequestBody Body;
        
        public GetBibleWordsByBookTitleAndChapterRequest()
        {
        }
        
        public GetBibleWordsByBookTitleAndChapterRequest(SOAPService.GetBibleWordsByBookTitleAndChapterRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
    public partial class GetBibleWordsByBookTitleAndChapterRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BookTitle;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int chapter;
        
        public GetBibleWordsByBookTitleAndChapterRequestBody()
        {
        }
        
        public GetBibleWordsByBookTitleAndChapterRequestBody(string BookTitle, int chapter)
        {
            this.BookTitle = BookTitle;
            this.chapter = chapter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBibleWordsByBookTitleAndChapterResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBibleWordsByBookTitleAndChapterResponse", Namespace="http://www.webserviceX.NET", Order=0)]
        public SOAPService.GetBibleWordsByBookTitleAndChapterResponseBody Body;
        
        public GetBibleWordsByBookTitleAndChapterResponse()
        {
        }
        
        public GetBibleWordsByBookTitleAndChapterResponse(SOAPService.GetBibleWordsByBookTitleAndChapterResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
    public partial class GetBibleWordsByBookTitleAndChapterResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBibleWordsByBookTitleAndChapterResult;
        
        public GetBibleWordsByBookTitleAndChapterResponseBody()
        {
        }
        
        public GetBibleWordsByBookTitleAndChapterResponseBody(string GetBibleWordsByBookTitleAndChapterResult)
        {
            this.GetBibleWordsByBookTitleAndChapterResult = GetBibleWordsByBookTitleAndChapterResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public interface BibleWebserviceSoapChannel : SOAPService.BibleWebserviceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public partial class BibleWebserviceSoapClient : System.ServiceModel.ClientBase<SOAPService.BibleWebserviceSoap>, SOAPService.BibleWebserviceSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BibleWebserviceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(BibleWebserviceSoapClient.GetBindingForEndpoint(endpointConfiguration), BibleWebserviceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BibleWebserviceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BibleWebserviceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BibleWebserviceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BibleWebserviceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BibleWebserviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPService.GetBibleWordsByChapterAndVerseResponse> SOAPService.BibleWebserviceSoap.GetBibleWordsByChapterAndVerseAsync(SOAPService.GetBibleWordsByChapterAndVerseRequest request)
        {
            return base.Channel.GetBibleWordsByChapterAndVerseAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPService.GetBibleWordsByChapterAndVerseResponse> GetBibleWordsByChapterAndVerseAsync(string BookTitle, int chapter, int Verse)
        {
            SOAPService.GetBibleWordsByChapterAndVerseRequest inValue = new SOAPService.GetBibleWordsByChapterAndVerseRequest();
            inValue.Body = new SOAPService.GetBibleWordsByChapterAndVerseRequestBody();
            inValue.Body.BookTitle = BookTitle;
            inValue.Body.chapter = chapter;
            inValue.Body.Verse = Verse;
            return ((SOAPService.BibleWebserviceSoap)(this)).GetBibleWordsByChapterAndVerseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPService.GetBibleWordsbyKeyWordResponse> SOAPService.BibleWebserviceSoap.GetBibleWordsbyKeyWordAsync(SOAPService.GetBibleWordsbyKeyWordRequest request)
        {
            return base.Channel.GetBibleWordsbyKeyWordAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPService.GetBibleWordsbyKeyWordResponse> GetBibleWordsbyKeyWordAsync(string BibleWords)
        {
            SOAPService.GetBibleWordsbyKeyWordRequest inValue = new SOAPService.GetBibleWordsbyKeyWordRequest();
            inValue.Body = new SOAPService.GetBibleWordsbyKeyWordRequestBody();
            inValue.Body.BibleWords = BibleWords;
            return ((SOAPService.BibleWebserviceSoap)(this)).GetBibleWordsbyKeyWordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPService.GetBookTitlesResponse> SOAPService.BibleWebserviceSoap.GetBookTitlesAsync(SOAPService.GetBookTitlesRequest request)
        {
            return base.Channel.GetBookTitlesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPService.GetBookTitlesResponse> GetBookTitlesAsync()
        {
            SOAPService.GetBookTitlesRequest inValue = new SOAPService.GetBookTitlesRequest();
            inValue.Body = new SOAPService.GetBookTitlesRequestBody();
            return ((SOAPService.BibleWebserviceSoap)(this)).GetBookTitlesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPService.GetBibleWordsByBookTitleAndChapterResponse> SOAPService.BibleWebserviceSoap.GetBibleWordsByBookTitleAndChapterAsync(SOAPService.GetBibleWordsByBookTitleAndChapterRequest request)
        {
            return base.Channel.GetBibleWordsByBookTitleAndChapterAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPService.GetBibleWordsByBookTitleAndChapterResponse> GetBibleWordsByBookTitleAndChapterAsync(string BookTitle, int chapter)
        {
            SOAPService.GetBibleWordsByBookTitleAndChapterRequest inValue = new SOAPService.GetBibleWordsByBookTitleAndChapterRequest();
            inValue.Body = new SOAPService.GetBibleWordsByBookTitleAndChapterRequestBody();
            inValue.Body.BookTitle = BookTitle;
            inValue.Body.chapter = chapter;
            return ((SOAPService.BibleWebserviceSoap)(this)).GetBibleWordsByBookTitleAndChapterAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BibleWebserviceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BibleWebserviceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BibleWebserviceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://www.webservicex.net/BibleWebservice.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.BibleWebserviceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://www.webservicex.net/BibleWebservice.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BibleWebserviceSoap,
            
            BibleWebserviceSoap12,
        }
    }
}
